### PR TITLE
2016 sponsor with levels

### PR DESCRIPTION
**Pull request by ar3**
Sooo @mileszs this one may be controversial... but putting the levels of the sponsorship on the site feels kinda icky, but kinda right as well.

If we don't put the level, we should at least put them in the order in which their sponsorship level indicates, and then maybe alphabetical?

### CODE REVIEW

**Comment by netshade** [comment]
Even though it's sort of the same thing, what do you think about saying "Food", "T-Shirts", "Beer", etc. instead of sponsorship levels, as then attendees have a more tangible way to connect what the sponsors did for the event.

**Comment by swanson** [comment]
I'll add this additional data point: higher tier sponsors get larger logos on the event poster (and placement at the top)

**Comment by mileszs** [comment]
@netshade The only downside there is that only 2 of the sponsors chose a level that we can directly connect to a tangible thing – t-shirts (MOBI) and drinks (Inverse Square).

**Comment by mileszs** [comment]
In general, though, I am pro- naming it after the thing instead of the level where we can. (T-Shirts instead of "Level that cannot be named" or whatever bullshit I made up.)

**Comment by ar3** [comment]
We can punt on this for this year (since naming things is hard, and we have other things that require our attention right now)... just something to think about next year!

**Pull request merged**
