### PR TITLE
Use same protocol to load CSS as is used to access the site

### PR DESCRIPTION
**Pull request by armilam**
If the site is loaded via HTTPS, use HTTPS.

### CODE REVIEW

**Comment by armilam** [comment]
I think this fixes it. I just need to test it.

**Comment by armilam** [comment]
Yep, I'm pretty sure that'll do it. If someone wants to approve it, I can deploy it.

**Comment by mike-rogers** [comment]
(stamp of approval)

the uh, build pipeline failure is a little disconcerting but i imagine that's a separate thingie

**Comment by armilam** [comment]
I personally have never seen the build pass on this repo. I don't know why. I may look into that some day.

**Pull request merged**
