### PR TITLE
Add photo galleries of past events to old event pages

### PR DESCRIPTION
**Pull request by netshade**
Since [Garrett](https://github.com/thirdshift) has captured photos for almost all the prior socials, thought it made sense to add links to his galleries on all the old event pages. We should probably get his permission before actually shipping this tho.

### CODE REVIEW

**Comment by thirdshift** [comment]
Indy Hackers has my permission to use my photos from the Indy Hackers Holiday Social whenever and wherever the organization wants to use them.

Combined in reverse chronilogical order: https://thirdshift.smugmug.com/All-Indy-Hackers-Holiday-Parti/
2015: https://thirdshift.smugmug.com/Indy-Hackers-2015/
2014: https://thirdshift.smugmug.com/2014-Indy-Hackers-Holiday-Soci/
2013: https://thirdshift.smugmug.com/Indy-Hackers-Holiday-Social/
2012: I think I was sick.
2011: https://thirdshift.smugmug.com/Other/Other-1/Indy-Hackers-Holiday-2011/n-qM6NZ/

**Comment by netshade** [comment]
Thanks @thirdshift !!!!!

**Comment by netshade** [comment]
( And, if you'd prefer that the images get hosted somewhere not-right-next-to-your-personal-photos, let me know and I'll scrape and re-host on S3 or something )

**Comment by thirdshift** [comment]
I don't care where they are hosted. Whatever works for you.

**Comment by netshade** [comment]
Cool, will just leave 'em where they stay for the time being. Thanks man. :)

**Comment by mileszs** [comment]
@netshade and @thirdshift, you guys are awesome.

**Pull request merged**
