### PR TITLE
3x3

### PR DESCRIPTION
**Pull request by ar3**

### CODE REVIEW

**Comment by netshade** [comment]
Note: image dimensions for changed images should be in 145x145, convert via:

```
convert <image-name> -resize "145x145" <output-image-name>
```

to get your headshot in correct dims. ( Assuming `imagemagick` installed )

**Comment by netshade** [comment]
Following folks should provide `145x145` versions of these headshots or be cursed to live in low-res griminess forever:

- [ ] Calvin
- [ ] Emily
- [ ] @jonfuller 
- [ ] @swanson 
- [ ] @ar3 
- [ ] @mileszs

**Comment by dstrus** [comment]
[image: Inline image 1]

**Comment by netshade** [comment]
I don't think that reply took, @dstrus , it just shows as "inline image" here in GH.

**Comment by dstrus** [comment]
dstrus-145x145

**Comment by mileszs** [comment]
:+1: Done

**Comment by netshade** [comment]
Closing in favor of #50

**Pull request closed without merging**
